version: '3.8'

services:
  simulator:
    image: seismic-signal-simulator:multiarch_v1
    ports:
      - "8080:8080"
    networks:
      - seismic-network

  broker:
    build: ./broker
    ports:
      - "5010:5001"
    networks:
      - seismic-network
    depends_on:
      - simulator
    environment:
      - FLASK_ENV=production
      - SIMULATOR_HOST=simulator

  frontend:
    build: ./frontend
    ports:
      - "5030:8080"
    networks:
      - seismic-network
    depends_on:
      - simulator
      - broker
    environment:
      - FLASK_ENV=production
      - BROKER_HOST=broker
      - BROKER_PORT=5001
  

  replica0:
    build: ./replica
    ports:
      - "5001:5000"
    networks:
      - seismic-network
    depends_on:
      - simulator
      - broker
    environment:
      - FLASK_ENV=production
      - SIMULATOR_HOST=simulator
      - BROKER_HOST=broker
      - BROKER_PORT=5001
  replica1:
    build: ./replica
    ports:
      - "5002:5000"
    networks:
      - seismic-network
    depends_on:
      - simulator
      - broker
    environment:
      - FLASK_ENV=production
      - SIMULATOR_HOST=simulator
      - BROKER_HOST=broker
      - BROKER_PORT=5001
  replica2:
    build: ./replica
    ports:
      - "5003:5000"
    networks:
      - seismic-network
    depends_on:
      - simulator
      - broker
    environment:
      - FLASK_ENV=production
      - SIMULATOR_HOST=simulator
      - BROKER_HOST=broker
      - BROKER_PORT=5001
  replica3:
    build: ./replica
    ports:
      - "5004:5000"
    networks:
      - seismic-network
    depends_on:
      - simulator
      - broker
    environment:
      - FLASK_ENV=production
      - SIMULATOR_HOST=simulator
      - BROKER_HOST=broker
      - BROKER_PORT=5001
  replica4:
    build: ./replica
    ports:
      - "5005:5000"
    networks:
      - seismic-network
    depends_on:
      - simulator
      - broker
    environment:
      - FLASK_ENV=production
      - SIMULATOR_HOST=simulator
      - BROKER_HOST=broker
      - BROKER_PORT=5001

  postgres:
    image: postgres:16
    container_name: fonchi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "fonchi4ever"
      POSTGRES_DB: FonchiDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - seismic-network
      
volumes:
  postgres_data:

networks:
  seismic-network:
    driver: bridge

